apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/team-4
  newTag: back-8221a82cbf7e9f194e0beb30d5a6069a80cfc7c1
- name: app
  newTag: main-3abede514e69bf831c9b14e42ca62ff7f179687a
- name: team-4
  newTag: main-f70f4538f95eb08343161647279571c2fdbdb250
resources:
- ../../resources/
